"""initial

Revision ID: 312f6a770f90
Revises: 
Create Date: 2026-08-24 00:08:28.515309
"""

import sqlalchemy as sa
from alembic import op


revision = '312f6a770f90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('transaction_type', sa.Enum('LOAN', 'EQUITY', 'SUKUK', 'PRIVATE_EQUITY', 'VENTURE_CAPITAL', 'REAL_ASSET', 'FUND_INTEREST', name='transactiontype', native_enum=False, length=32), nullable=False),
    sa.Column('compliance_mode', sa.Enum('TRADITIONAL', 'ISLAMIC', name='compliancemode', native_enum=False, length=32), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('issuer_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('type_specific_data', sa.JSON(), nullable=False),
    sa.Column('underlying_asset_description', sa.Text(), nullable=True),
    sa.Column('underlying_asset_id', sa.String(length=128), nullable=True),
    sa.Column('shariah_contract_type', sa.Enum('MURABAHA', 'IJARA', 'MUSHARAKAH', 'WAKALAH', 'NONE', name='shariahcontracttype', native_enum=False, length=32), nullable=True),
    sa.Column('shariah_review_status', sa.Enum('NOT_APPLICABLE', 'SYSTEM_FLAGGED_NONCOMPLIANT', 'PENDING_SCHOLAR_REVIEW', 'SCHOLAR_APPROVED', 'SCHOLAR_REJECTED', name='shariahreviewstatus', native_enum=False, length=48), nullable=False),
    sa.Column('shariah_reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('document_type', sa.Enum('TERM_SHEET', 'LOAN_AGREEMENT', 'SHA', 'PPM', 'LPA', 'SUKUK_CERTIFICATE', 'FATWA', 'FINANCIAL_STATEMENT', 'KYC', 'SIDE_LETTER', 'SAFE', 'UNCLASSIFIED', 'OTHER', name='documenttype', native_enum=False, length=64), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_schema_name', sa.String(length=255), nullable=False),
    sa.Column('extraction_schema_version', sa.String(length=32), nullable=False),
    sa.Column('ingestion_source', sa.Enum('NATIVE_EXTRACTION', 'VENDOR_IMPORT', 'MANUAL_ENTRY', name='ingestionsource', native_enum=False, length=32), nullable=False),
    sa.Column('compliance_mode', sa.Enum('TRADITIONAL', 'ISLAMIC', name='compliancemode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'REVIEW_NEEDED', 'FAILED', name='documentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('shariah_review_status', sa.Enum('NOT_APPLICABLE', 'SYSTEM_FLAGGED_NONCOMPLIANT', 'PENDING_SCHOLAR_REVIEW', 'SCHOLAR_APPROVED', 'SCHOLAR_REJECTED', name='shariahreviewstatus', native_enum=False, length=48), nullable=False),
    sa.Column('shariah_reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('shariah_validation_errors', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'file_url', name='uq_document_instrument_file')
    )
    op.create_index('ix_documents_instrument_id', 'documents', ['instrument_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entry_type', sa.Enum('CATEGORY_MUTATION', 'DOCUMENT_RESULT', 'COMPLIANCE_EVENT', name='ledgerentrytype', native_enum=False, length=48), nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('raw_input', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_created_at', 'ledger_entries', ['created_at'], unique=False)
    op.create_index('ix_ledger_document_id', 'ledger_entries', ['document_id'], unique=False)
    op.create_index('ix_ledger_instrument_id', 'ledger_entries', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_instrument_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_document_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_created_at', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_documents_instrument_id', table_name='documents')
    op.drop_table('documents')
    op.drop_table('instruments')
    # ### end Alembic commands ###